### ISSUE TITLE
Serializer, Django

### ISSUE THREAD

**Issue by slovoyolo121** [Shved15/django-freelance-exchange#1]
cloned your repository, launched the project to dig into it, changed something for myself, such an error popped up, I just can’t decide, can you help

```
Internal Server Error: /api/user/32a1c34eab8d4ba3ad4670adc50467d5/
Traceback (most recent call last):
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/rest_framework/fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/rest_framework/fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Http404' has no attribute 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slovo11/Desktop/django-freelance-exchange/allapps/user/serializers.py", line 19, in to_representation
    representation = super().to_representation(instance)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slovo11/Desktop/django-freelance-exchange/venv/lib/python3.11/site-packages/rest_framework/fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `username` on serializer `UserSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `type` instance.
Original exception text was: type object 'Http404' has no attribute 'username'.
```

**Comment by Shved15** [comment]
This error occurs when trying to get the value of the username attribute from an Http404 object that does not have that attribute.

To fix this error, you need to find the place in the code where it tries to get the value of the username attribute from the Http404 object and fix it to the correct object that has the username attribute.

It may also help to rename the field according to an attribute or key that is present on the instance that the serializer is working with.
